# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color
  ALACRITTY: "1"

window:
  padding:
   x: 3
   y: 3

  decorations: full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

scrolling:
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Mononoki Nerd Font Mono
    style: Regular

  # Point size
  size: 16.0

  # Offset is the extra space around each character.
  # `offset.y` can be thought of as modifying the line spacing.
  offset:
    x: 1
    y: 1

