#!/bin/sh

# Global settings.
# layout bsp or float (default: bsp)
yabai -m config layout bsp

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_shadow                float


# Gaps and Margins.
GAP_SIZE=2
yabai -m config top_padding                  ${GAP_SIZE}
yabai -m config bottom_padding               ${GAP_SIZE}
yabai -m config left_padding                 ${GAP_SIZE}
yabai -m config right_padding                1 #${GAP_SIZE}
yabai -m config window_gap                   ${GAP_SIZE}

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier               fn
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1                move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2                resize

