local attach = require 'ps.lsp.attach'
local handlers = require 'ps.lsp.handlers'
local capabilities = require 'ps.lsp.capabilities'

-- sourcekit-lsp ships with the active Xcode toolchain. `xcrun --find
-- sourcekit-lsp` always resolves to the toolchain selected by xcode-select,
-- so it stays correct even after a toolchain upgrade without config changes.
--
-- Explicit fallback to the known absolute path in case xcrun is not on PATH
-- inside neovim's environment (e.g. when launched from a launcher rather than
-- a terminal).
local function find_sourcekit_lsp()
  local xcrun = vim.fn.exepath('xcrun')
  if xcrun ~= '' then
    local result = vim.fn.system('xcrun --find sourcekit-lsp 2>/dev/null')
    local path = vim.trim(result)
    if path ~= '' and vim.fn.executable(path) == 1 then
      return path
    end
  end
  -- Hardcoded fallback — update if you switch Xcode installs.
  local fallback =
    '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp'
  if vim.fn.executable(fallback) == 1 then
    return fallback
  end
  return 'sourcekit-lsp'
end

return {
  cmd = { find_sourcekit_lsp() },
  filetypes = { 'swift', 'objc', 'objcpp', 'objective-c', 'objective-cpp' },
  capabilities = capabilities.get(),
  handlers = handlers.default(),
  on_attach = attach.with_default_config,

  -- sourcekit-lsp discovers the build system by walking up from the open file
  -- looking for: buildServer.json > Package.swift > *.xcodeproj/xcworkspace.
  -- For Xcode projects the reliable path is a buildServer.json in the project
  -- root generated by xcode-build-server (see notes in this file's header).
  root_markers = {
    'buildServer.json',   -- xcode-build-server — preferred for Xcode projects
    'Package.swift',      -- SwiftPM projects
    '*.xcworkspace',
    '*.xcodeproj',
    '.git',
  },

  -- Initialization options are sent once during the LSP handshake (initialize
  -- request). sourcekit-lsp reads backgroundIndexing here, not from
  -- workspace/didChangeConfiguration, so it must live in init_options.
  init_options = {
    -- Show inlay hints for parameter labels and result types.
    -- Toggle at runtime with: vim.lsp.inlay_hint.enable(true)
    ["sourcekit-lsp.inlayHints.enabled"] = true,

    -- Background indexing lets sourcekit-lsp build its own index so
    -- go-to-definition and find-references work without a prior Xcode build.
    -- sourcekit-lsp reads this from initializationOptions, not from
    -- workspace/didChangeConfiguration. Disable if CPU usage is excessive.
    backgroundIndexing = true,
  },
}
