export CFGS=$HOME/dotfiles

source $CFGS/bash/bashrc_main.sh

# ---------------------------------------------------------------------------- #

# Use GNU coreutils installed via homebrew instead of macOS defaults.
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"